# -*- coding: utf-8 -*-
"""optimizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bgJheBRhVY_WM9onL9jBlDZVFjr1ULag
"""

# Unimos plantilla + mercado en un único pool de candidatos
df_pool = pd.concat([df_team_full, df_market_full], ignore_index=True)
df_pool = df_pool.drop_duplicates(subset="id")  # por si acaso se solapa algún id
df_pool = df_pool.dropna(subset=["price", "price_change"]) #qquitar NaN

columns = ["id", "name", "position", "price", "price_change", "team_id", 'owner_id']

def resumen(df_resultado, capital, columns):
    print(f"Gasto total: {df_resultado['price'].sum():,.0f}")
    print(f"Ganancia esperada: {df_resultado['price_change'].sum():,.0f}")
    print(f"Jugadores: {len(df_resultado)} / capital: {capital:,.0f}")
    display(df_resultado[columns])



def GreedyAlgorithmC(df_in, capital, max_jugadores=25, max_por_equipo=3):
    df = df_in.copy()
    df['ROI_diario'] = df['price_change'] / df['price']
    df = df.sort_values(by='ROI_diario', ascending=False)

    compras = []
    gasto_total = 0
    conteo_equipos = {}

    for _, player in df.iterrows():
        if player['price_change'] <= 0:
            continue
        if len(compras) >= max_jugadores:
            break  # ya no caben más, sea cual sea el ROI del resto
        if gasto_total + player['price'] > capital:
            continue

        equipo = player['team_id']
        if conteo_equipos.get(equipo, 0) >= max_por_equipo:
            continue

        compras.append(player)
        gasto_total += player['price']
        conteo_equipos[equipo] = conteo_equipos.get(equipo, 0) + 1

    return pd.DataFrame(compras)

lista_optima = GreedyAlgorithmC(df_pool, capital)
'''
resumen(lista_optima, capital, columns)
'''



import pulp

def OptimalAlgorithm(df_in, capital, max_jugadores=25, max_por_equipo=3):
    df = df_in.reset_index(drop=True)
    prob = pulp.LpProblem("fantasy_optimo", pulp.LpMaximize)

    # una variable binaria por jugador: 1 si lo compras, 0 si no
    x = [pulp.LpVariable(f"x_{i}", cat="Binary") for i in df.index]

    # objetivo: maximizar la suma de revalorizaciones esperadas
    prob += pulp.lpSum(df.loc[i, "price_change"] * x[i] for i in df.index)

    # restricción de presupuesto
    prob += pulp.lpSum(df.loc[i, "price"] * x[i] for i in df.index) <= capital

    # restricción de plantilla máxima
    prob += pulp.lpSum(x[i] for i in df.index) <= max_jugadores

    # restricción de máximo N por equipo real
    for equipo in df["team_id"].dropna().unique():
        idx_equipo = df[df["team_id"] == equipo].index
        prob += pulp.lpSum(x[i] for i in idx_equipo) <= max_por_equipo

    prob.solve(pulp.PULP_CBC_CMD(msg=0))

    seleccionados = [i for i in df.index if x[i].value() == 1]
    return df.loc[seleccionados]

lista_optima_pulp = OptimalAlgorithm(df_pool, capital)

'''
resumen(lista_optima_pulp, capital, columns)

'''