# -*- coding: utf-8 -*-
"""scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196XpwKQpLcZpdAl-6LjWlXnzjTpcLYjc
"""

from curl_cffi import requests
from bs4 import BeautifulSoup
import pandas as pd
import re


url = "https://fantasy.marca.com/market"

RAW_COOKIE = r"""_____COOKIE HERE________"""
safe_cookie = RAW_COOKIE.strip().encode("ascii", "ignore").decode("ascii")

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "es-ES,es;q=0.9,en;q=0.8",
    "X-Auth": "______YOUR AUTH HERE_______",
    "Cookie": safe_cookie,
    "x-community-id": "_____YOUR LEAGUE ID______",
    "X-Requested-With": "XMLHttpRequest",
    "Origin": "https://fantasy.marca.com",
    "Referer": "https://fantasy.marca.com/team",
}

response = requests.post(url, headers=headers, impersonate="chrome")
print("Status Code:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

players_market = []
for li in soup.select("#list-on-sale > li"):
    name_tag = li.select_one(".name")
    link_tag = li.select_one("a.player")
    arrow_tag = li.select_one(".value-arrow")

    href = link_tag["href"] if link_tag else None
    player_id = href.split("/")[1] if href else None

    trend = None
    if arrow_tag:
        classes = arrow_tag.get("class", [])
        if "green" in classes:
            trend = "sube"
        elif "red" in classes:
            trend = "baja"
    team_logo = li.select_one(".icons img.team-logo")
    team_id = None
    if team_logo and team_logo.get("src"):
        match = re.search(r"/teams/(\d+)\.png", team_logo["src"])
        if match:
            team_id = match.group(1)



    players_market.append({
        "id": player_id,
        "name": name_tag.get_text(strip=True) if name_tag else None,
        "position": li.get("data-position"),
        "price": int(li.get("data-price")) if li.get("data-price") else None,
        "owner_id": li.get("data-owner"),
        "loanable": li.has_attr("data-loanable"),
        "ends": pd.to_datetime(li.get("data-ends"), unit="s") if li.get("data-ends") else None,
        "trend": trend,
        "url": f"https://fantasy.marca.com/{href}" if href else None,
        "team_id": team_id,
    })

df_market = pd.DataFrame(players_market)

######################################################################################################################33

url_team = "https://fantasy.marca.com/team"

response = requests.post(url_team, headers=headers, impersonate="chrome")
soup = BeautifulSoup(response.text, "html.parser")

# --- Info general de la plantilla ---
squad_info = soup.select_one(".squad-info")
title_text = squad_info.select_one(".title").get_text(strip=True)          # "21/25 jugadores"
subtitle_text = squad_info.select_one(".subtitle").get_text(" ", strip=True)  # "€ 270.154.000 · 6.005.000 ↑"

# --- Jugadores ---
players_team = []
for li in soup.select("ul.list-team > li"):
    player_id = li["id"].replace("player-", "") if li.has_attr("id") else None

    link_tag = li.select_one("a.player")
    href = link_tag["href"] if link_tag else None

    name_tag = li.select_one(".name")
    position_tag = li.select_one(".player-position")
    under_name = li.select_one(".underName")
    arrow_tag = under_name.select_one(".value-arrow") if under_name else None
    owner_btn = li.select_one("button.btn-sale")

    # el precio viene mezclado en el texto ("€ 30.353.000"), lo limpiamos
    price = None
    if under_name:
        match = re.search(r"([\d.]+)", under_name.get_text())
        if match:
            price = int(match.group(1).replace(".", ""))

    trend = None
    if arrow_tag:
        classes = arrow_tag.get("class", [])
        if "green" in classes:
            trend = "sube"
        elif "red" in classes:
            trend = "baja"

    team_logo = li.select_one(".icons img.team-logo")
    team_id = None
    if team_logo and team_logo.get("src"):
        match = re.search(r"/teams/(\d+)\.png", team_logo["src"])
        if match:
            team_id = match.group(1)

    players_team.append({
        "id": player_id,
        "name": name_tag.get_text(strip=True) if name_tag else None,
        "position": position_tag.get("data-position") if position_tag else None,
        "price": price,
        "trend": trend,
        "owner_id": owner_btn.get("data-id_owner") if owner_btn else None,
        "url": f"https://fantasy.marca.com/{href}" if href else None,
        "team_id": team_id,
    })

df_team = pd.DataFrame(players_team)

##############################################################################3333

def get_player_change(player_id, slug, headers):
    payload = {
        "post": "players",
        "id": player_id,
        "slug": slug,
        "comments": 0,
    }
    resp = requests.post(
        "https://fantasy.marca.com/ajax/sw/players",
        headers=headers,
        data=payload,
        impersonate="chrome",
    )
    if resp.status_code != 200:
        return None, None

    data = resp.json().get("data", {})
    values = data.get("values", [])
    if values:
        latest = values[0]  # el primero es el más reciente ("Un día")
        return latest.get("value"), latest.get("change")
    return None, None


# --- Aplicarlo a todo el equipo ---
changes = []
for _, row in df_team.iterrows():
    href = row["url"].replace("https://fantasy.marca.com/", "")  # "players/31/jan-oblak"
    parts = href.split("/")
    player_id, slug = parts[1], parts[2]

    value, change = get_player_change(player_id, slug, headers)
    changes.append({"id": row["id"], "current_value": value, "price_change": change})

df_changes = pd.DataFrame(changes)
df_team_full = df_team.merge(df_changes, on="id", how="left")

##################################################################################################333

def enrich_with_change(df, headers, delay=0.3):
    changes = []
    for _, row in df.iterrows():
        href = row["url"].replace("https://fantasy.marca.com/", "")
        parts = href.split("/")
        player_id, slug = parts[1], parts[2]

        value, change = get_player_change(player_id, slug, headers)
        changes.append({"id": row["id"], "current_value": value, "price_change": change})

        time.sleep(delay)  # para no saturar el servidor con cientos de peticiones seguidas

    df_changes = pd.DataFrame(changes)
    return df.merge(df_changes, on="id", how="left")


import time

df_market_full = enrich_with_change(df_market, headers)  # "df" es tu DataFrame del mercado

#################################################################################

url_balance = "https://fantasy.marca.com/ajax/balance"

response = requests.post(url_balance, headers=headers, impersonate="chrome")
balance_data = response.json()["data"]

print("Saldo actual:", balance_data["current"])
print("Saldo futuro (tras operaciones pendientes):", balance_data["future"])
print("Deuda máxima permitida:", balance_data["maxDebt"])

jugadores = int(title_text.split('/')[0])
valor_equipo = int(subtitle_text.split(' ')[1].replace('.', ''))
print(f'jugadores: {jugadores}')
print(f'valor_equipo: {valor_equipo}')


capital = valor_equipo + balance_data['maxDebt']
print(f'capital: {capital}')